# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_save_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(757, 82)
        self.checkBox_db_zaiku = QtWidgets.QCheckBox(Form)
        self.checkBox_db_zaiku.setGeometry(QtCore.QRect(10, 20, 75, 16))
        self.checkBox_db_zaiku.setObjectName("checkBox_db_zaiku")
        self.checkBox_db_dingdan = QtWidgets.QCheckBox(Form)
        self.checkBox_db_dingdan.setGeometry(QtCore.QRect(92, 20, 75, 16))
        self.checkBox_db_dingdan.setObjectName("checkBox_db_dingdan")
        self.checkBox_db_paichu = QtWidgets.QCheckBox(Form)
        self.checkBox_db_paichu.setGeometry(QtCore.QRect(174, 20, 75, 16))
        self.checkBox_db_paichu.setObjectName("checkBox_db_paichu")
        self.checkBox_open_hong = QtWidgets.QCheckBox(Form)
        self.checkBox_open_hong.setGeometry(QtCore.QRect(256, 20, 75, 16))
        self.checkBox_open_hong.setObjectName("checkBox_open_hong")
        self.checkBox_auto_up = QtWidgets.QCheckBox(Form)
        self.checkBox_auto_up.setGeometry(QtCore.QRect(336, 20, 75, 16))
        self.checkBox_auto_up.setObjectName("checkBox_auto_up")
        self.checkBox_auto_next = QtWidgets.QCheckBox(Form)
        self.checkBox_auto_next.setGeometry(QtCore.QRect(417, 20, 75, 16))
        self.checkBox_auto_next.setObjectName("checkBox_auto_next")
        self.pushButton_open = QtWidgets.QPushButton(Form)
        self.pushButton_open.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.pushButton_open.setObjectName("pushButton_open")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(91, 50, 75, 23))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_next = QtWidgets.QPushButton(Form)
        self.pushButton_next.setGeometry(QtCore.QRect(173, 50, 75, 23))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_get_order = QtWidgets.QPushButton(Form)
        self.pushButton_get_order.setGeometry(QtCore.QRect(254, 50, 75, 23))
        self.pushButton_get_order.setObjectName("pushButton_get_order")
        self.pushButton_re_order = QtWidgets.QPushButton(Form)
        self.pushButton_re_order.setGeometry(QtCore.QRect(335, 50, 75, 23))
        self.pushButton_re_order.setObjectName("pushButton_re_order")
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        self.pushButton_exit.setGeometry(QtCore.QRect(416, 50, 75, 23))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(500, 15, 241, 22))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "打开保存文件"))
        self.checkBox_db_zaiku.setText(_translate("Form", "对比在库"))
        self.checkBox_db_dingdan.setText(_translate("Form", "对比定单"))
        self.checkBox_db_paichu.setText(_translate("Form", "对比排除"))
        self.checkBox_open_hong.setText(_translate("Form", "打开宏"))
        self.checkBox_auto_up.setText(_translate("Form", "自动上传"))
        self.checkBox_auto_next.setText(_translate("Form", "自动next"))
        self.pushButton_open.setText(_translate("Form", "Open"))
        self.pushButton_save.setText(_translate("Form", "Save"))
        self.pushButton_next.setText(_translate("Form", "Next()"))
        self.pushButton_get_order.setText(_translate("Form", "Get_order"))
        self.pushButton_re_order.setText(_translate("Form", "Re_order"))
        self.pushButton_exit.setText(_translate("Form", "Exit"))
