# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_Qoo10.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(495, 72)
        self.checkBox_zaiku_down = QtWidgets.QCheckBox(Form)
        self.checkBox_zaiku_down.setGeometry(QtCore.QRect(10, 15, 71, 16))
        self.checkBox_zaiku_down.setObjectName("checkBox_zaiku_down")
        self.checkBox_dingdan_down = QtWidgets.QCheckBox(Form)
        self.checkBox_dingdan_down.setGeometry(QtCore.QRect(86, 15, 71, 16))
        self.checkBox_dingdan_down.setObjectName("checkBox_dingdan_down")
        self.checkBox_dingdan_work = QtWidgets.QCheckBox(Form)
        self.checkBox_dingdan_work.setGeometry(QtCore.QRect(162, 15, 71, 16))
        self.checkBox_dingdan_work.setObjectName("checkBox_dingdan_work")
        self.checkBox_dingdan_up = QtWidgets.QCheckBox(Form)
        self.checkBox_dingdan_up.setGeometry(QtCore.QRect(238, 15, 71, 16))
        self.checkBox_dingdan_up.setObjectName("checkBox_dingdan_up")
        self.checkBox_youji_up = QtWidgets.QCheckBox(Form)
        self.checkBox_youji_up.setGeometry(QtCore.QRect(314, 15, 101, 16))
        self.checkBox_youji_up.setObjectName("checkBox_youji_up")
        self.checkBox_zaiku_up = QtWidgets.QCheckBox(Form)
        self.checkBox_zaiku_up.setGeometry(QtCore.QRect(86, 42, 47, 16))
        self.checkBox_zaiku_up.setObjectName("checkBox_zaiku_up")
        self.checkBox_select_all = QtWidgets.QCheckBox(Form)
        self.checkBox_select_all.setGeometry(QtCore.QRect(162, 42, 47, 16))
        self.checkBox_select_all.setObjectName("checkBox_select_all")
        self.lineEdit_zaiku_up_num = QtWidgets.QLineEdit(Form)
        self.lineEdit_zaiku_up_num.setGeometry(QtCore.QRect(10, 40, 61, 23))
        self.lineEdit_zaiku_up_num.setObjectName("lineEdit_zaiku_up_num")
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(410, 40, 77, 23))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setGeometry(QtCore.QRect(313, 40, 77, 23))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.checkBox_zaiku_file_up = QtWidgets.QCheckBox(Form)
        self.checkBox_zaiku_file_up.setGeometry(QtCore.QRect(420, 15, 71, 16))
        self.checkBox_zaiku_file_up.setObjectName("checkBox_zaiku_file_up")
        self.pushButton_set_config = QtWidgets.QPushButton(Form)
        self.pushButton_set_config.setGeometry(QtCore.QRect(220, 40, 75, 23))
        self.pushButton_set_config.setObjectName("pushButton_set_config")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_zaiku_down.setText(_translate("Form", "在库下载"))
        self.checkBox_dingdan_down.setText(_translate("Form", "定单下载"))
        self.checkBox_dingdan_work.setText(_translate("Form", "定单处理"))
        self.checkBox_dingdan_up.setText(_translate("Form", "定单上传"))
        self.checkBox_youji_up.setText(_translate("Form", "クリックポスト上传"))
        self.checkBox_zaiku_up.setText(_translate("Form", "出库"))
        self.checkBox_select_all.setText(_translate("Form", "全选"))
        self.lineEdit_zaiku_up_num.setPlaceholderText(_translate("Form", "出库行号"))
        self.pushButton_start.setText(_translate("Form", "开始(Ct+F11)"))
        self.pushButton_stop.setText(_translate("Form", "停止(Ct+F12)"))
        self.checkBox_zaiku_file_up.setText(_translate("Form", "出库上传"))
        self.pushButton_set_config.setText(_translate("Form", "配置选项"))
